# Marqo endpoint (your Cloudflare URL)
MARQO_URL = "https://marqo.logicafutura.com"

# If you protected Marqo with Cloudflare Access Service Token:
CF_ACCESS_CLIENT_ID = "568a3e766d1ec15f5812fa1099b07219.access"
CF_ACCESS_CLIENT_SECRET = "89666e51d5dcdab32e631aaddc8fa5736004ede064a5f92bcf5b5e9ee6dae25c"
