# Marqo
MARQO_URL = "https://marqo.logicafutura.com"
INDEX_NAME = "furniture-index"
TITLE_FIELD = "title"
IMAGE_FIELD = "image"
ALT_IMAGE_FIELD = "image_vendor_url"
DOMINANT_COLOR_FIELD = "dominant_color"
SKU_FIELD = "sku"

# Cloudflare Access (Service Token protecting Marqo)
CF_ACCESS_CLIENT_ID = "<your-access-client-id>"
CF_ACCESS_CLIENT_SECRET = "<your-access-client-secret>"

# Cloudflare R2 (S3 compatible)
R2_ENDPOINT_URL = "https://a02844df1d7dc6554edd401be979b64a.r2.cloudflarestorage.com"
R2_ACCESS_KEY_ID = "<your-r2-access-key>"
R2_SECRET_ACCESS_KEY = "<your-r2-secret-key>"
R2_BUCKET = "streamlit098"

# Public base that serves your bucket (must end with /)
# If you didn't set a custom domain, use the r2.dev public URL:
PUBLIC_BASE_URL = "https://pub-a02844df1d7dc6554edd401be979b64a.r2.dev/streamlit098/"
