# Marqo
MARQO_URL = "https://marqo.logicafutura.com"
INDEX_NAME = "furniture-index"
TITLE_FIELD = "title"
IMAGE_FIELD = "image"
ALT_IMAGE_FIELD = "image_vendor_url"
DOMINANT_COLOR_FIELD = "dominant_color"
SKU_FIELD = "sku"

# Cloudflare Access (Service Token protecting Marqo)
CF_ACCESS_CLIENT_ID = "568a3e766d1ec15f5812fa1099b07219.access"
CF_ACCESS_CLIENT_SECRET = "89666e51d5dcdab32e631aaddc8fa5736004ede064a5f92bcf5b5e9ee6dae25c"

# Cloudflare R2 (S3 compatible)
R2_ENDPOINT_URL = "https://a02844df1d7dc6554edd401be979b64a.r2.cloudflarestorage.com"
R2_ACCESS_KEY_ID = "315398485b6e17f63c559f8bd9221b4a"
R2_SECRET_ACCESS_KEY = "4dfdd1fe3b8b9ab562c5b8336d0d94cab164cea1aa58e6bef054dbb833a87e01"
R2_BUCKET = "streamlit098"

# Public base that serves your bucket (must end with /)
# If you didn't set a custom domain, use the r2.dev public URL:
PUBLIC_BASE_URL = "https://pub-a02844df1d7dc6554edd401be979b64a.r2.dev/streamlit098/"
